<<<<<<< HEAD
#os: osx
#osx_image: xcode12.2
#language: swift
#script: xcodebuild clean build test -quiet -workspace Messenger_2.xcworkspace/ -scheme "Messenger_2" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.0" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NOl

language : swift
osx_image : xcode12.2
xcode_workspace : Messenger_2.xcworkspace
xcode_scheme : Messenger_2
xcode_destination : platform=iOS Simulator,OS=14.4,name=iPhone 11
