os: osx
osx_image: xcode12.2
language: swift
<<<<<<< HEAD
script: xcodebuild clean build test -quiet -workspace Messenger_2.xcworkspace/ -scheme "Messenger_2" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NOl
=======
script: xcodebuild clean build test -quiet -workspace Messenger_2.xcworkspace/ -scheme "Messenger_2" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
>>>>>>> e5a615df2c8434e00d47402b446233b06acee713
