os: osx
osx_image: xcode12.2
language: swift
script: travis_wait 30 xcodebuild clean build test -quiet -workspace Messenger_2.xcworkspace/ -scheme "Messenger_2" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NOl
